### ISSUE TITLE
Is it possible to hide leading stars in no window mode?

### ISSUE THREAD

**Issue by dackon** [emacsorphanage/org-bullets#6]
I can see leading stars if I run 'emacs -nw', is it possible to hide them? Thanks

**Comment by integral-dw** [comment]
It is, simply set the Org variable `org-hide-leading-stars` to `t` in your config.  This will set the font used for them to the face `org-hide` which you can configure like any other face (ideally it should blend with the background to truly hide the stars).  However, that is the maximum of hiding possible in org-bullets.  The stars usually will still show up when you, for example, mark regions of text, which can be a little disconcerting.  If you want them gone for good, a possible solution is using the org-superstar package instead, where you can set up leading stars to look like spaces (or other things like decorative characters) in every way.

**Comment by dackon** [comment]
Doesn't work, in emacs no window mode I still can see the stars. If in emacs window mode, it works. But I only work in no window mode, I don't use emacs window mode.

**Comment by integral-dw** [comment]
Hm, in that case, mind showing me a screenshot of how it looks, together with your current value for the face `org-hide`?

**Comment by dackon** [comment]
Sorry, I skipped face org-hide, just set foreground color to color-231, works prefect, thank you very much

**Comment by integral-dw** [comment]
You're welcome!
