### ISSUE TITLE
Missing third and fourth symbol

### ISSUE THREAD

**Issue by bkaczynski** [emacsorphanage/org-bullets#7]
I can't event paste it directly to buffer, but I can use it in for example Kate (KDE Text Editor). Anyone know how can I fix this?

![Screenshot_20200914_205815](https://user-images.githubusercontent.com/37001658/93126849-310ebf00-f6cd-11ea-8ceb-8384b6c1c918.png)
![Screenshot_20200914_210220](https://user-images.githubusercontent.com/37001658/93127304-f0fc0c00-f6cd-11ea-8896-4c64673c435a.png)

**Comment by tarsius** [comment]
Either use a different font that has these symbols, or use different symbols that your current font has. The latter is probably preferable.

**Comment by bkaczynski** [comment]
I explicitly added to my init file:
`(add-to-list 'default-frame-alist
	     '(font . "DejaVu Sans Mono-10"))
`
and that solve the problem.
